endpoints: 
  map: 
    http_method: get
    mappables: 
      name: downtown_yoga_shala
      address: 450 S. First Street San Jose, CA 95113
  view: 
    http_method: get
    viewables:
      name: downtown_yoga_shala
      description:     
  create: 
    http_method: post
    receivables: 
      name:
      description:
      address:      